services:
  - type: web
    name: fake-news-detection
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    pythonVersion: 3.10.13
    autoDeploy: true
